/**
 * Daily P&L Report — runs pnl-aggregator for the last 24h and writes a
 * Markdown report to logs/daily/YYYY-MM-DD.md.
 *
 * Usage:
 *   npx ts-node scripts/daily-pnl-report.ts
 *
 * Scheduled via cron: daily at 23:59 UTC.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import { execSync } from 'node:child_process';

const LOGS_DIR = path.join('logs', 'daily');

function ensureDir(dir: string) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

function runReport(): string {
  // Run the pnl-aggregator for last 1 day, JSON output
  const cmd = 'npx ts-node scripts/pnl-aggregator.ts --days 1 --json';
  const stdout = execSync(cmd, { encoding: 'utf-8', timeout: 30_000 });
  return stdout;
}

function formatSOL(sol: number): string {
  return `${sol >= 0 ? '+' : ''}${sol.toFixed(6)} SOL`;
}

function formatUSD(usd: number): string {
  return `${usd >= 0 ? '+' : ''}$${usd.toFixed(2)}`;
}

function generateMarkdown(report: any, dateStr: string): string {
  const lines: string[] = [];
  const today = new Date().toISOString().slice(0, 10);

  lines.push(`# Daily P&L Report — ${today}`);
  lines.push('');
  lines.push(`Generated: ${new Date().toISOString()}`);
  lines.push('');
  lines.push('## Summary');
  lines.push('');
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Total Trades | ${report.totalTrades} |`);
  lines.push(`| Executed | ${report.executedTrades} |`);
  lines.push(`| Skipped | ${report.skippedTrades} |`);
  lines.push(`| Failed | ${report.failedTrades} |`);
  lines.push(`| Gross P&L (SOL) | ${formatSOL(report.grossProfitSOL)} |`);
  lines.push(`| Gross P&L (USD) | ${formatUSD(report.grossProfitUSD)} |`);
  lines.push(`| Net P&L (SOL) | ${formatSOL(report.netProfitSOL)} |`);
  lines.push(`| Net P&L (USD) | ${formatUSD(report.netProfitUSD)} |`);
  lines.push(`| Total Fees (SOL) | ${formatSOL(report.totalFeesSOL)} |`);
  lines.push(`| Total Fees (USD) | ${formatUSD(report.totalFeesUSD)} |`);
  lines.push(`| Win Rate | ${(report.winRate * 100).toFixed(1)}% |`);
  lines.push(`| Avg Profit % | ${(report.avgProfitPct * 100).toFixed(2)}% |`);
  lines.push(`| Best Trade | ${formatSOL(report.bestTradeSOL)} (${report.bestTradePair}) |`);
  lines.push(`| Worst Trade | ${formatSOL(report.worstTradeSOL)} (${report.worstTradePair}) |`);

  if (report.daily && report.daily.length > 0) {
    lines.push('');
    lines.push('## Daily Breakdown');
    lines.push('');
    lines.push(`| Date | Executed | Skipped | Failed | Net P&L (SOL) | Fees (SOL) | Win Rate |`);
    lines.push(`|------|---------:|-------:|------:|:-------------:|:----------:|:--------:|`);
    for (const day of report.daily) {
      const pnl = formatSOL(day.netProfitSOL);
      const fees = formatSOL(day.totalFeeSOL);
      const winRate = `${(day.winRate * 100).toFixed(0)}%`;
      lines.push(`| ${day.date} | ${day.executed} | ${day.skipped} | ${day.failed} | ${pnl} | ${fees} | ${winRate} |`);
    }
  }

  if (report.totalTrades === 0) {
    lines.push('');
    lines.push('⚠️ No trade logs found for this period.');
  }

  lines.push('');
  lines.push('---');
  lines.push(`_Report generated by scripts/daily-pnl-report.ts_`);

  return lines.join('\n');
}

function main() {
  const dateStr = new Date().toISOString().slice(0, 10);
  ensureDir(LOGS_DIR);

  const reportPath = path.join(LOGS_DIR, `${dateStr}.md`);

  try {
    const raw = runReport();
    const report = JSON.parse(raw);
    const markdown = generateMarkdown(report, dateStr);
    fs.writeFileSync(reportPath, markdown, 'utf-8');
    console.log(`✅ Daily P&L report written to ${reportPath}`);
  } catch (err) {
    // Write a minimal report indicating failure
    const fallback = [
      `# Daily P&L Report — ${dateStr}`,
      '',
      `Generated: ${new Date().toISOString()}`,
      '',
      '⚠️ Report generation failed.',
      '',
      `Error: ${err instanceof Error ? err.message : String(err)}`,
      '',
      '---',
      '_Report generated by scripts/daily-pnl-report.ts_',
    ].join('\n');
    fs.writeFileSync(reportPath, fallback, 'utf-8');
    console.error(`❌ P&L report failed: ${err}`);
    process.exit(1);
  }
}

main();